### ISSUE TITLE
Support for lengthMenu

### ISSUE THREAD

**Issue by stefankaifer** [LZorglub/DataTables.AspnetCore.Mvc#10]
Thank you for this great contribution.

I'm missing the possibility to set the lengthMenu property. Can you implement it?

`        $('#example').DataTable({
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]]
        });`

https://datatables.net/examples/advanced_init/length_menu.html

Maybee you can create an option to insert PROPERTY-VALUE-pairs in general.

**Comment by LZorglub** [comment]
You can specify the length menu with package version 1.4.2.0

`@(Html.Ext().Grid<Product>().Name("example").RowId("id")
            .LengthMenu(c =>
            {
                c.Add(new int[] { 10, 25, 50 });
                c.Add(-1, "All");
            })
`

You can found an example in the demo project under the server side page.

**Comment by stefankaifer** [comment]
many thanks!
