### ISSUE TITLE
Typo in DataTableColumn

### ISSUE THREAD

**Issue by klaus-liebler** [LZorglub/DataTables.AspnetCore.Mvc#3]
https://github.com/LZorglub/DataTables.AspnetCore.Mvc/blob/51bbc1e745b423c479c13386a2404678cf5be288/DataTables.AspNetCore.Mvc/Binder/DataTableColumn.cs#L23

Replace
this.SearchValue = SearchValue;
this.SearchRegEx = SearchRegEx;
With          
this.SearchValue = searchValue;
this.SearchRegEx = regex;

**Comment by LZorglub** [comment]
Fixed
