### ISSUE TITLE
Possibility to add custom css class to table

### ISSUE THREAD

**Issue by cfasol** [LZorglub/DataTables.AspnetCore.Mvc#4]
Hi, it would be useful to add a custom css class to the table tag in order to customize the table created with a framework like boostrap etc.

thank you 
regards

**Comment by LZorglub** [comment]
Hi,

You can now customize the css class by providing list of css

```
        @(Html.Ext().Grid<dynamic>().Name("example")
            .ClassName("dataTable")
```

regards
