### ISSUE TITLE
Render is currently broken on 1.3.0?

### ISSUE THREAD

**Issue by Beffyman** [LZorglub/DataTables.AspnetCore.Mvc#8]
Render does not appear to be functioning correctly on the current 1.3.0 package.
Example branch where the package is installed instead of using a project reference.
https://github.com/Beffyman/DataTables.AspnetCore.Mvc/tree/example/CurrentPackageRenderIssue

Running the demo and looking at the ServerSide page shows that Renders aren't written to the table def json.

Any chance you can publish a 1.3.1/1.4.0?
(And can you include #7 in it if you do?)

**Comment by LZorglub** [comment]
Package 1.4.1 published with fix
