### ISSUE TITLE
Support for jquery defer loading

### ISSUE THREAD

**Issue by arulchris** [LZorglub/DataTables.AspnetCore.Mvc#9]
_Thank you for this great contribution._
When jquery loading is deferred, as of now we get error $ is not defined and datatable initialization fails. It would be great if you could add support for this.

**Comment by LZorglub** [comment]
Thanks,
If you reference jQuery inside the Head section of your page, jQuery will be available and ready to use.

**Comment by arulchris** [comment]
But, even if it is added in head section same will happen. as the datatable initialization is done through in-line javascript. _This is a Feature Request._
